### ISSUE TITLE
Typo detected on the Azure Credits FAQ page 

### ISSUE THREAD

**Issue by bijoy26** [microsoft/opensource.microsoft.com#129]
### **Location**: [opensource.microsoft.com/azure-credits#credits-faq](https://opensource.microsoft.com/azure-credits#credits-faq)
 
![image](https://user-images.githubusercontent.com/42487891/135671110-cf88b7ea-0d6c-4a27-8529-e642dd0466dd.png)

**Fix**: `insfrastructure` ❌ should be `infrastructure` ✅

Submitting an external PR sounds overkill for this. 😅 Still let me know if I should do it anyway.

**Comment by jeffwilcox** [comment]
Thanks, appreciate it. Looks like it was directly fixed in commit https://github.com/microsoft/opensource.microsoft.com/commit/eee52a39146f2dac74abffe23cc27214da57edeb
