### ISSUE TITLE
REST API for repos should pull in topics

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource.microsoft.com#14]

**Comment by jeffwilcox** [comment]
I've verified there is more backend work required on this one.

**Comment by nash567** [comment]
I want to contribute in this issue.What should  i do to solve the issue.

**Comment by bharath2131** [comment]
i can resolve this issue

**Comment by Aaron-Junker** [comment]
> i can resolve this issue

@jeffwilcox @emmairwin

**Comment by jeffwilcox** [comment]
Unfortunately this issue requires backend changes that are in a closed-source API server. This is tracked here for transparency. I'm going to remove the stale label but am not sure when this could improve. Once the API server is updated, the frontend would need corresponding fixes, too.
