### ISSUE TITLE
Add download links to the projects

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#157]
Add an optional new field in projects for downloading the open sorce project.

An example: 

![image](https://user-images.githubusercontent.com/58633848/149373862-7b4f3916-bce6-40ce-bc4f-97b114858b92.png)

I would like to make a PR which implements this, if you like the idea.

**Comment by Aaron-Junker** [comment]
@jeffwilcox Any thoughts for my suggestion?

**Comment by jeffwilcox** [comment]
Happy to accept contributions to the site where it makes sense. @emmairwin  and @fossygirl may be able to help coordinate. We're not actively working on this public site today on the team but are always happy to try and collaborate.

**Comment by emmairwin** [comment]
I personally love that idea @Aaron-Junker
Maybe adding in some limitations on where downloads may come from  (like the store, or GitHub)?

**Comment by Aaron-Junker** [comment]
> I personally love that idea @Aaron-Junker
> Maybe adding in some limitations on where downloads may come from  (like the store, or GitHub)?

I think limiting it to the store would be the best solution.

**Comment by emmairwin** [comment]
Ok, I think yes please if you are willing that would be great to have your contribution around this.
I can test on my end, if you provide steps for that in the PR.  Thanks very much!
