### ISSUE TITLE
PowerToys has three dots in link.

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#158]
The PowerToys project has three dots after the link description. No other project has this.

![image](https://user-images.githubusercontent.com/58633848/149374238-71ce75a8-2ae3-4e49-b317-43e1663f565f.png)

I would be more then happy to create a PR to change this.

cc: @crutkas

**Comment by crutkas** [comment]
good eye, if you'd like to, please do

**Comment by Aaron-Junker** [comment]
> good eye, if you'd like to, please do

Done #159
