### ISSUE TITLE
update footer items on tablet

### ISSUE THREAD

**Issue by Arhell** [microsoft/opensource.microsoft.com#167]
![Screenshot_3](https://user-images.githubusercontent.com/26163841/152576311-9779898b-0c07-4a91-97ce-b2e835d57dcc.png)

**Comment by emmairwin** [comment]
Hi @Arhell thanks for this, how can I reporduce?  What kind of tablet, what browser, resolution etc.

**Comment by Arhell** [comment]
As shown in the screenshot above, the resolution is 1024 pixels and up to 1150.
Bowser chrome, edge, firefox.
In principle, it does not depend on the browser, but on the width of the screen.
already fixed it too https://github.com/microsoft/opensource.microsoft.com/pull/168
