### ISSUE TITLE
header bug

### ISSUE THREAD

**Issue by Arhell** [microsoft/opensource.microsoft.com#178]
When scrolling, the header disappears, but you can click on it
![Screenshot_1](https://user-images.githubusercontent.com/26163841/155878717-5bc9debc-de67-454d-a498-00df1cc34d6c.png)

**Comment by emmairwin** [comment]
Hi @Arhell what are the steps to reproduce?

**Comment by Arhell** [comment]
> Hi @Arhell what are the steps to reproduce? cc/ @Aaron-Junker we can't fix what we can't reproduce. We may consider having a issue template that includes a question around this. Pretty common in issue templates, and probably one we can borrow from another project.

I already fixed this issue https://github.com/microsoft/opensource.microsoft.com/pull/179
When you scroll the header disappears and you can click on it. I fixed it.
