### ISSUE TITLE
Feature calculator in projects

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#180]
[microsoft/calculator](https://github.com/microsoft/calculator) is a very important peoject, because it ships with every installation of Windows, but it isn't featured on the projects page. 

In my opinion it should be added.

**Comment by emmairwin** [comment]
Sounds good,  if someone wants to submit a PR that would be great.

**Comment by santoshmanaguli** [comment]
I can do this. will you assign it to me

**Comment by Aaron-Junker** [comment]
> I can do this. will you assign it to me

Thank you! I assigned you.

**Comment by LOGOLFGODORD** [comment]
probably not ! i dont trust many from git hub!

**Comment by jamesiri** [comment]
@santoshmanaguli assigned issue to you.

**Comment by LOGOLFGODORD** [comment]
Yes please ill trust you .please be repectful to my advice

**Comment by jamesiri** [comment]
Removed two comments as they had no relation to the package or the problem at hand.

**Comment by jeffwilcox** [comment]
@Aaron-Junker what should we do on this one, not sure if you wanted to submit the PR, or should we close?

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker what should we do on this one, not sure if you wanted to submit the PR, or should we close?

I would like to do this, when you approve

**Comment by jeffwilcox** [comment]
@Aaron-Junker ready anytime to review a PR
