### ISSUE TITLE
Add overview of Microsoft Github organisations

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#182]
There are many Microsoft (Partner) Organisations on Github and I think an overview wouldn't be bad. Something like the project overview page.

For example:

* [Microsoft](//github.com/microsoft)
* [Microsoft Docs](//github.com/microsoftdocs)
* [.Net](https://github.com/dotnet)
* etc.

**Comment by emmairwin** [comment]
The Microsoft GitHub organization is the main org for Microsoft   We do link out to projects like .NET on our projects page, and while you and I might be interested in the GH organization of projects, its not high level enough to highlight.  Thanks for the proposal though!
