### ISSUE TITLE
Add new labels

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#186]
I would like to suggest the following new labels:

|Name|Description|
|-------|------------|
|In progress|To mark issues as in progress|
|Idea-general|Ideas for general things related to Microsoft Open Source|

And delete the documentation label, because we don't really have docs

**Comment by akshatcoder-hash** [comment]
Hey @Aaron-Junker , I would love to work on this issue. Could you please assign it to me?
Also, is there any slack or a community where discussion is possible regarding the issues?

**Comment by akshatcoder-hash** [comment]
Hey @Aaron-Junker , I would love to work on this issue. Could you please assign it to me?
Also, is there any slack channel or a community forum where discussion is possible regarding the issues?

**Comment by Aaron-Junker** [comment]
Hi @akshatcoder-hash. Thank you for showing interest in working on this issue. However adding labels is a thing only people with write permissions can do and you don't have them.

> Also, is there any slack channel or a community forum where discussion is possible regarding the issues?

No this repo does not have something like this. The discussions stay in the issues.

**Comment by akshatcoder-hash** [comment]
I am sorry if this looks like a foolish question, but is it possible that I can get 'write' permission?

**Comment by Aaron-Junker** [comment]
> I am sorry if this looks like a foolish question, but is it possible that I can get 'write' permission?

I'm not the one who can decide this. But as much as we love community contributions, for me it seems a bit off to just give someone "write" permissions just to add 2 labels and delete one.

I will add @emmairwin and @jamesiri here.

If you have any further questions please feel free to ask them.

**Comment by emmairwin** [comment]
I think that a discussion about labels can happen without having permission to implement the fix.
I think its best when proposing labels to have a problem you hope to solve, and then how you would measure success. 

Also if there are other projects using labels, its always great to leverage standards already proven, or tested in other communities (even if they would be a bit different).

**Comment by emmairwin** [comment]
@akshatcoder-hash what type of things are you interested in working on?

**Comment by emmairwin** [comment]
Hi, there is now an in progress label, but decided againstg idea-general, I don't think this label would be helpful in sorting, preferring specific titles to general.  Thanks for the suggestion!
