### ISSUE TITLE
Update FOSS Fund (Ecosystem) Page

### ISSUE THREAD

**Issue by emmairwin** [microsoft/opensource.microsoft.com#194]
We're missing the names/logos of a few recent FOSS Fund Winners
- OpenStreetMap
- MySyS2
- curl
- Reproducable Builds
- Babel
- Optikey

Full list (with links to projects)  should match the README: https://github.com/microsoft/foss-fund/blob/main/README.md

**Comment by Aaron-Junker** [comment]
I mean these ones: 
![Screenshot_20220406_072730](https://user-images.githubusercontent.com/58633848/161902035-3fb2f202-d634-46b5-a4ac-c7937cd93f83.jpg).

On the front page. They are saved under the _posts folder.

**Comment by emmairwin** [comment]
Its adding to this page  view of FOSS Fund winners (not posts)  on the Ecosystem Page  https://opensource.microsoft.com/ecosystem/
![image](https://user-images.githubusercontent.com/60618/162027830-16d381b8-83c2-4e39-8693-514f3171459e.png)

**Comment by balajik10** [comment]
Hi I want to work on this issue. Will you please assign this to me?

**Comment by Aaron-Junker** [comment]
> Hi I want to work on this issue. Will you please assign this to me?

Hi @balajik10. Thank you for your interest in working on this. I will assign this issue to you. Don't hesitate to ask questions if you have them.

**Comment by balajik10** [comment]
Thank you sir for assigning this issue to me , actually I got to know about git and github yesterday . to be frank I know basic c programming and currently I am learning python and I am interested in wed development , cloud computing, and some more interesting topics. 
Sir can you please guid me to solve this issue.

**Comment by Aaron-Junker** [comment]
> Thank you sir for assigning this issue to me , actually I got to know about git and github yesterday . to be frank I know basic c programming and currently I am learning python and I am interested in wed development , cloud computing, and some more interesting topics. 
> Sir can you please guid me to solve this issue.

@balajik10 Contributing to a open source project is a great opportunity to learn!

I will try to explain it to you:

So, on the [ecosystem page](https://opensource.microsoft.com/ecosystem/) there's a list with all projects sponsored by the FOSS fund. Some projects are missing (see issue text above). Every project is in a own file in the [_fossfund folder](https://github.com/microsoft/opensource.microsoft.com/tree/main/_fossfund).

Just follow the existing items to create new ones or update the ones that are already there. 

Images of the projects are saved here: https://github.com/microsoft/opensource.microsoft.com/tree/main/assets/images/fossfund

I hope this helps to start. Please don't hesitate to ask further questions. 

Thanks again!

**Comment by balajik10** [comment]
Thank you for responding , now I have locked and cloned the issue in my desktop.
what should I do next ?
does C-language help me in this issue in any manner or should I want to learn any other language.

Thanks again!

**Comment by balajik10** [comment]
Sorry sir if I am troubling you a lot .
this is my first time for GitHub stuff and it will be really helpful if you will guide me on the first issue.

**Comment by Aaron-Junker** [comment]
No. This project doesn't use C as a programming language. The files in the linked fossfund folder are all written in [front matter](https://jekyllrb.com/docs/front-matter/).

**Comment by Aaron-Junker** [comment]
> Sorry sir if I am troubling you a lot .
> this is my first time for GitHub stuff and it will be really helpful if you will guide me on the first issue.

You're not troubling at all. I'm here to help you. Is what I wrote in the comment clear  or not? If not I will try to specify it.

**Comment by balajik10** [comment]
sorry , I am not clear about it.

**Comment by Aaron-Junker** [comment]
> sorry , I am not clear about it.

Ok. Let's go through this step by step. Afterwards please point out the steps that aren't clear for you. 

1. This issue is about the following page: https://opensource.microsoft.com/ecosystem/ . On this page there are several projects sponsered by the FOSS fund.

![Screenshot_20220423_203441.jpg](https://user-images.githubusercontent.com/58633848/164943660-b05148bd-fc98-44c8-be5f-8508460f18d0.jpg)

2. Every single one of these entries are one file in the folder called: `_fossfund`: https://github.com/microsoft/opensource.microsoft.com/tree/main/_fossfund

3. Some of them are outdated or are missing information. These ones are listed on the top of this issue.

4. The files are all structured like this:

```
---
title: <name of the project>
logo: <name of the logo image>
projectUrl: <url of the project>
linkText: "<text of the link>" 
description: "<description of the project>" 
processing: "<award process>"
context: "<why project was awarded>"
awarded: true 
fund: "FOSS Fund #<number>"
---
```

You just have to replace the things in the \<\> brackets. I think when you look at the existing files you get how they are structured.

5. The current information can be found here: https://github.com/microsoft/foss-fund

I hope this made it a bit clearer. If not please point out the numbers you didn't understand.

**Comment by balajik10** [comment]
Hi thank you for explaining me in depth, it helped a lot.
I have updated the files and do a pull request, now they are saying to sign the CLA.
Can you please explain me what is CLA before I sign in.

**Comment by Aaron-Junker** [comment]
> Hi thank you for explaining me in depth, it helped a lot.
> I have updated the files and do a pull request, now they are saying to sign the CLA.
> Can you please explain me what is CLA before I sign in.

I've answered your question in the Pull Request.

**Comment by balajik10** [comment]
hey Aaron, I have a question about the "1 workflow awaiting approval". 
and when will my pull request be merged

**Comment by Aaron-Junker** [comment]
> hey Aaron, I have a question about the "1 workflow awaiting approval". 
> and when will my pull request be merged

As @emmairwin said in your Pull Request she will have a look at it today. She also can approve the workflow then.

**Comment by balajik10** [comment]
OK , Thank you for the information.
