### ISSUE TITLE
Update issue template to include steps to reproduce

### ISSUE THREAD

**Issue by Aaron-Junker** [microsoft/opensource.microsoft.com#195]
We may consider having a issue template that includes a question around this.  Pretty common in issue templates, and probably one we can borrow from another project.

_Originally posted by @emmairwin in https://github.com/microsoft/opensource.microsoft.com/issues/178#issuecomment-1089625911_

**Comment by bhavyastar** [comment]
I want to work on this issue. Will you please assign this to me?

**Comment by Aaron-Junker** [comment]
> I want to work on this issue. Will you please assign this to me?
> 

Thank you for your interest in working on this. I assigned it to you. 

Please don't hesitate to ask questions if you have them.

**Comment by bhavyastar** [comment]
> > I want to work on this issue. Will you please assign this to me?
> 
> Thank you for your interest in working on this. I assigned it to you.
> 
> Please don't hesitate to ask questions if you have them.

Okay, sir, Thank you so much. 😃 @Aaron-Junker. 
Is there any discord or slack server where if I have any doubts I can ask those?

**Comment by Aaron-Junker** [comment]
> > > I want to work on this issue. Will you please assign this to me?
> > 
> > Thank you for your interest in working on this. I assigned it to you.
> > 
> > Please don't hesitate to ask questions if you have them.
> 
> Okay, sir, Thank you so much. 😃 @Aaron-Junker. 
> Is there any discord or slack server where if I have any doubts I can ask those?

No. If you have doubts or questions you can ask them here in this issue.

**Comment by Aaron-Junker** [comment]
@bhavyastar Hi I just wanted to ask if everything is clear and if you're still interested in doing this?

**Comment by bhavyastar** [comment]
Hey @Aaron-Junker, Everything is clear, I am going to make a Pull Request for the same in 1-2 days! Thank you!

**Comment by Aaron-Junker** [comment]
> Hey @Aaron-Junker, Everything is clear, I am going to make a Pull Request for the same in 1-2 days! Thank you!

Great!

**Comment by bhavyastar** [comment]
Hello @Aaron-Junker, Sorry for the delay, stuck with my exams, going to make Pull Request for the same after 26 May, Is it okay?

**Comment by Aaron-Junker** [comment]
> Hello @Aaron-Junker, Sorry for the delay, stuck with my exams, going to make Pull Request for the same after 26 May, Is it okay?

Yeah sure. Take the time you need.

**Comment by emmairwin** [comment]
I have renamed thiss to help circle back to the goal

**Comment by emmairwin** [comment]
https://github.com/microsoft/opensource.microsoft.com/commit/807ebaf21d11f1a5c284387696cca0ce4b62057f
