### ISSUE TITLE
[BUG] Project link broken

### ISSUE THREAD

**Issue by yuvalherziger** [microsoft/opensource.microsoft.com#202]
## Summary

The link to `colorma` OSS project is interpreted as a relative path of `opensource.microsoft.com/ecosystem`, resulting in an inevitable 404.

## Steps to Reproduce

1. Browse to [https://opensource.microsoft.com/ecosystem/](https://opensource.microsoft.com/ecosystem/)
2. Scroll down to where OSS project tiles are displayed
4. Click the link to `https://github.com/tartley/colorama`
    - **BUG:** the link is interpreted as a relative path of `opensourse.microsoft.com/ecosystem` and the computed link is `https://opensource.microsoft.com/ecosystem/github.com/tartley/colorama`, which obviously doesn't exist.

![Screen_Shot_2022-04-24_at_14_03_52](https://user-images.githubusercontent.com/5735586/164973435-8357dff7-9edc-4a07-81a7-0fc82ed2bf21.png)

**Comment by Aaron-Junker** [comment]
I can confirm this linktext and projecturl are mixed up.
