### ISSUE TITLE
Add `.devcontainer.json` to repository 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [microsoft/opensource.microsoft.com#206]
I can see instructions on building this repository with codespaces in the README https://github.com/microsoft/opensource.microsoft.com#developing-with-codespaces, but I don't see the `devcontainer.json` configuration file in the repository. 

Should we add that in here to help newcomers or even existing people, so that their codespace machine will be set up right from the beginning so that they will be more focused on making functional changes rather than getting dependencies installed and configured!?

**Comment by Aaron-Junker** [comment]
+1 for this idea

**Comment by emmairwin** [comment]
Hi @ShreyasJejurkar yes please do propose a PR if you are still intereted.  Thanks!

**Comment by LOGOLFGODORD** [comment]
Don’t touch nor am I giving you promise or promotion to touch any of my property!!!! Thanks !! And no thanks the government can do all that ! You don’t have the write to change nor take action on behalf of others coding !! Who’s is giving you this code of conduct ? Tell me there address and offering as is immediately!

**Comment by koudaiii** [comment]
Hi, Recently, I sent a pull request. ref #221 
Can someone please review it?

**Comment by koudaiii** [comment]
Thank you for your time and your review. 😄 
I commented.　https://github.com/microsoft/opensource.microsoft.com/pull/221#issuecomment-1206157700

**Comment by koudaiii** [comment]
Is there anything I should do to get this Pull Request merged?  Also, who does the merging? @emmairwin ?

**Comment by koudaiii** [comment]
Recently #221 merged. Can we close this issue? @ShreyasJejurkar @emmairwin @Aaron-Junker
