### ISSUE TITLE
implementation of new languages ​​to facilitate the work?

### ISSUE THREAD

**Issue by sebastianjnuwu** [microsoft/opensource.microsoft.com#213]
There are some other nice languages ​​to use example svelte an idea just "-'"

**Comment by Aaron-Junker** [comment]
I personally don't see the point in changing the framework. I think we should focus more on delivering great content

Cc: @jamesiri @emmairwin

**Comment by jamesiri** [comment]
While there are many great languages and frameworks out there we are secure and confident in our selections for this project.

If you wanted to fork this project and convert it I would absolutely encourage it, but it isn't something that we have the desire to pursue..
