### ISSUE TITLE
Code of Conduct not found (404)

### ISSUE THREAD

**Issue by rjmholt** [microsoft/opensource.microsoft.com#30]
https://opensource.microsoft.com/codeofconduct/ seems to have disappeared, causing [failures in PowerShell's static analysis CI steps](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=60439&view=logs&jobId=20040542-2952-5caf-d527-1a6ae3d90bed&j=20040542-2952-5caf-d527-1a6ae3d90bed&t=2df8e2d5-8210-54c4-1b7f-4b7ab92a2712).

I notice that links on https://opensource.microsoft.com point to the same URL and also 404.

Is there an alternate URL we should point to?

**Comment by rjmholt** [comment]
https://opensource.microsoft.com/code-of-conduct seems to be the correct URL now

**Comment by rjmholt** [comment]
Fixed in https://github.com/microsoft/opensource.microsoft.com/commit/282b1c7e0bf70732d7a02ad68d90352902aa8a2d

**Comment by jeffwilcox** [comment]
Thanks for pointing this out!
