### ISSUE TITLE
Search performance could be improved

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource.microsoft.com#31]
There seem to be a few issues with our rather basic JS experience of pulling the query and showing results. An initial pre-load UI might be helpful, and I've seen a race condition where it shows the most popular repos but never the search contents.

**Comment by jeffwilcox** [comment]
Race condition fixed in https://github.com/microsoft/opensource.microsoft.com/commit/7c7d7bec6905e8c37bb68753fa1d88e0efa8b283

**Comment by Aaron-Junker** [comment]
> Race condition fixed in [7c7d7be](https://github.com/microsoft/opensource.microsoft.com/commit/7c7d7bec6905e8c37bb68753fa1d88e0efa8b283)

@jeffwilcox When it's fixed this can get closed right?
