### ISSUE TITLE
Not able to open .msg and .eml files with New Outlook Version(1.2023.515.100 (Production)).

### ISSUE THREAD

**Issue by kapilbisht94** [microsoft/opensource.microsoft.com#313]
**Describe the bug**
We are not able to open our .msg and .eml files of outlook with the New Outlook version(1.2023.515.100 (Production)). Although, it is working fine for old version.
**To Reproduce**
1. Open the Outlook latest version(1.2023.515.100 (Production)) or switch to New Outlook if you're using old one. 
2. Now, Select any EMail from Inbox.
3. From Right panel, tap on Ellipses and Tap on Download to download the email.
4. Now, Try to open the downloaded .eml File.
5. Observe that it is not allowing user to open it as shared in screenshot.

**Expected behavior**
User should be able to open .msg and .eml files from New Outlook.

**Screenshots**
![image](https://github.com/microsoft/opensource.microsoft.com/assets/68806319/4121de1e-19ec-442d-b377-3a9a2d7c93ec)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop App
 - Outlook version [1.2023.515.100 (Production)]

**Comment by Aaron-Junker** [comment]
This repo is for issues related to the OSPO website. Please xontact Microsoft Support and report the problem there
