### ISSUE TITLE
broken links to the Microsoft GitHub Policy Service

### ISSUE THREAD

**Issue by AnthonyByansi** [microsoft/opensource.microsoft.com#318]
**Describe the bug**
The links are broken

**To Reproduce**
1. Go to 'https://github.com/apps/microsoft-github-policy-service'
2. Click on 'https://github.com/microsoft/GitOps' or 'website'
3. See error

**Expected behavior**
Links should be working appropriately without 404 error.

**Comment by I-MirzaBaig** [comment]
Hi, Can i work on this issue?
seems like i kind off fix this!, As far as i know according to my knowledge. There can be many reasons why 404 error is occuring, but these two reasons might cause major 404 error, i.e its:-

1). DNS settings issue. Either the domain is still propagating or pointing to a wrong [DNS address].
2). Missing asset. Usually, any missing asset, such as an image, CSS, or JavaScript file, can generate a 404 error.
