### ISSUE TITLE
Codespaces never starts

### ISSUE THREAD

**Issue by JustinGOSSES** [microsoft/opensource.microsoft.com#327]
**Describe the bug**
The code spaces never fully starts but appears to stale out in "" stage where the message below is shown in the terminal

```
Use Cmd/Ctrl + Shift + P -> View Creation Log to see full logs
✔ Finishing up...
⠋ Running postCreateCommand...
  › jekyll server
```
**To Reproduce**
1. Click the big green "code" button the repository home page
3. Then click the "codespaces" button 
4. Then click the plus sign looking button to create a new codespace
5. When the VS Code editor starts, it shows the text above but never ends the "Finishing up" stage and gives you a working terminal to use.

**Expected behavior**
The "postCreateCommand" should eventually finish and the terminal appear with a blinking cursor. 

**Additional context**
Tried this on the main branch of the repository and in a forked version of the repository.

**Comment by JustinGOSSES** [comment]
Unsure if relevant information or not, but including in case it helps debug codespaces: 

Had trouble getting this to build and serve on Codespaces and Windows 11. Eventually got it to work on WSL by installing new versions of ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu] and Node.js v14.15.0. 

It seemed there were problems with the node.js node-sass package and other versions of node.js on windows.

**Comment by jeffwilcox** [comment]
Sounds like @capfei might have it working OK with a minor change to the devcontainer

**Comment by JustinGOSSES** [comment]
closing as problem seems fixed
