### ISSUE TITLE
Good first issue experiences need to be more useful

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource.microsoft.com#34]
As pointed out by @riverar, the soft launch experience needs to catch-up to the goals we had originally on having a more interactive experience.

**Comment by riverar** [comment]
Appreciate the quick handling of my knee-jerk complaint, hah! Just to add a bit more detail ...

I see **Help wanted** and **Get started** as key features and am personally looking to use them to see where I can help out. (An example of the Get Started experience is pictured below.)

Some concerns/thoughts regarding these experiences:

* The pause/resume controls at the top of the page seem to only apply to the "Happening now" feature, yet all these sub-areas appear to be live
* Get Started and similar lists only contain 6 items
  * As a dev, I expected to see a search box and pagination for each sub-grouping
* Get Started and similar lists don't convey which tags are being used for categorization. This impacts devs in that they can't workaround the 6 item limit by re-using that criteria on GitHub to find other potentially more interesting items to work on.
* Get Started and similar lists don't have clickable tags, making the above even harder.

![image](https://user-images.githubusercontent.com/475132/90078306-51f08880-dcb9-11ea-8cdc-f40dcb853b7d.png)

**Comment by thriftykapila** [comment]
Can you add me for this task, I want to work on this issue

**Comment by riverar** [comment]
Looks like a Hacktoberfest spammer.

**Comment by entrepernuer** [comment]
> 
> 
> Can you add me for this task, I want to work on this issue

GitHub is supposed to be open source

**Comment by entrepernuer** [comment]
Sorry about that forgot to read the contributing guidelines now I understand
