### ISSUE TITLE
Is this a web portal to https://github.com/microsoft ?

### ISSUE THREAD

**Issue by sequoiar** [microsoft/opensource.microsoft.com#35]

**Comment by jeffwilcox** [comment]
Not necessarily, we'd prefer people just hit GitHub directly for working on projects there... but for anyone looking to get high-level information about some of the projects, products, other open source activities Microsoft is a part of, it's a good resource for that.

The project explore experience is able to search some repos, but it's not a primary goal of the site.

How can I help?
