### ISSUE TITLE
Add 'Go' and 'Rust' filters to the explore projects page

### ISSUE THREAD

**Issue by craiglpeters** [microsoft/opensource.microsoft.com#37]
Go is the language of choice for much of the industry's infrastructure code, and Microsoft is no exception. There should be a 'Go' filter on the https://opensource.microsoft.com/projects/explore/ page.

Having said that, Rust is also an up and coming language for many of our projects. 

Skipping these two omits key parts of our ecosystem from the filter

**Comment by TylerLeonhardt** [comment]
I was originally coming in to this issue to say "Also add a PowerShell filter" but filters could probably be built dynamically based on the languages used of the repos.

**Comment by jeffwilcox** [comment]
Agreed @TylerLeonhardt... the site is funky in that it's mostly static, but we absolutely do have the language data and could pull that. For now I think we may add PowerShell manually as we fix a few bugs in the filtering!

**Comment by TylerLeonhardt** [comment]
Sounds good 🙂

**Comment by craiglpeters** [comment]
I think this is pretty important because if the filters don't reflect the nature of our contributions, then we give a wrong impression to the casual browser

**Comment by brunoborges** [comment]
Missing `Java` in the filter as well.

**Comment by virtualritz** [comment]
+1
