### ISSUE TITLE
Ecosystem Link Bugs (undefined and typo in external URLs)

### ISSUE THREAD

**Issue by bnb** [microsoft/opensource.microsoft.com#38]
Currently, if you click an issue from https://opensource.microsoft.com/ecosystem/, it goes to something like this:

```
https://github.com/org/repo/issue/276
```

there's a small typo there - it should be like this, with an `s` on `issues`:

```
https://github.com/org/repo/issues/276
```

Additionally, some entries like this one:

![image](https://user-images.githubusercontent.com/502396/90154907-ac8cf180-dd58-11ea-9de8-18f7ba7f1207.png)

Go to a url with `undefined` in them:

```
https://github.com/undefined/stevenbrix/xamlx-winui/pull/2
```

Removing that `undefined` goes to the correct link.

The only thing I've noticed there is that these ones have an additional leading `/` where others that work do not.

**Comment by jeffwilcox** [comment]
Thank you! A fix has been submitted to the backend API server and will roll out now.

Interestingly, pull requests are at `pull/:id` and the list at `pulls/`, while issues are at `issues/:number` and the list at `issues/`.
