### ISSUE TITLE
https://opensource.microsoft.com/ "not ready"

### ISSUE THREAD

**Issue by Xiphoseer** [microsoft/opensource.microsoft.com#396]
**Describe the bug**
<https://opensource.microsoft.com/> returns `200 OK` with a body of `Service not ready.`

**To Reproduce**
1. Go to <https://opensource.microsoft.com/>
2. See error

**Expected behavior**
The content from this repository be served, in particular [index.html](https://github.com/microsoft/opensource.microsoft.com/blob/main/index.html)

**Screenshots**
![image](https://github.com/microsoft/opensource.microsoft.com/assets/14206221/d9b29372-4c5a-4069-9d0b-a4b6f4f3c14b)
![image](https://github.com/microsoft/opensource.microsoft.com/assets/14206221/5de60fd6-96aa-4586-9cec-b2c33525b974)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 23H2
 - Browser: Microsoft Edge for Business, Version 124.0.2478.105 (Offizielles Build) (64-Bit)

**Additional context**
Encountered when clicking on <https://opensource.microsoft.com/cla> on a Microsoft Azure repository.

**Comment by Aaron-Junker** [comment]
It's not appearing for me. Maybe it was temporarily. Can you check if it still happens?

**Comment by Xiphoseer** [comment]
> It's not appearing for me. Maybe it was temporarily. Can you check if it still happens?

Seems fixed on my end as well :thumbsup:
