### ISSUE TITLE
Simple icons and Microsoft icons

### ISSUE THREAD

**Issue by dweber019** [microsoft/opensource.microsoft.com#405]
I did not know where to put this feedback but as it's around the great culture of open source maybe here is a good place.
I think you are really missing out here https://github.com/simple-icons/simple-icons/issues/11236
Would really like to see Microsoft icons in this repository along with the other brands.

https://github.com/simple-icons/simple-icons/pull/10019

**Comment by Aaron-Junker** [comment]
Cc: @emmairwin
