### ISSUE TITLE
cla link returns a 404

### ISSUE THREAD

**Issue by mattgreg** [microsoft/opensource.microsoft.com#41]
To reproduce the 404:

1. Go to https://opensource.microsoft.com/ecosystem/
1. Click `Microsoft Contributor License Agreement` in the blue section near the bottom of the page
1. You will land here: https://cla.opensource.microsoft.com/
1. Click `Microsoft Contributor License Agreement (CLA)`
1. redirect to here: https://opensource.microsoft.com/pdf/microsoft-contribution-license-agreement.pdf
1. returns 404

**Comment by jeffwilcox** [comment]
Thank you @mattgreg :gift_heart:

Fixed now in https://github.com/microsoft/opensource.microsoft.com/commit/a5fd0ff5e6c2c3550d1bfdc043a9751df0b0d376
