### ISSUE TITLE
"docker build" error

### ISSUE THREAD

**Issue by AevaOnline** [microsoft/opensource.microsoft.com#49]
`docker build .` yields the following error:

`Error response from daemon: Dockerfile parse error line 10: unknown instruction: ./NODE_MODULES/GULP/BIN/GULP.JS`

It appears to be an error on this line
https://github.com/microsoft/opensource.microsoft.com/blob/e862ec188971f1e01a37041f6e746c9366628e9c/Dockerfile#L10

I tried the simple fix of prefixing this line with the `RUN` directive, which did not work, so I am unsure what the intent of the existing line is.

Current docker version: 19.03.8
OS: Ubuntu 20.04.1

**Comment by jeffwilcox** [comment]
Great find! Heh. We're not actively actually using the Dockerfile so it hasn't been tested lately... will take a look.

**Comment by jeffwilcox** [comment]
The fix you suggested worked on my machine! Pushed a fix.
