### ISSUE TITLE
Is the backend api open source?

### ISSUE THREAD

**Issue by ppejovic** [microsoft/opensource.microsoft.com#65]
Is the backend that generates the activity feed(s) (e.g. `/api/stream`) for the _Get Involved_ part of site open source? I tried to look for it, apologies if I missed it.

**Comment by jeffwilcox** [comment]
No apologies needed... unfortunately, the backend is currently not entirely open source; however, I can probably help point you to what we've done: we connect to webhooks and then do a certain amount of processing there, and I think it would be straightforward to open source much of that.

The static portion of the site is built with Jekyll, but then we augment that with the backend APIs that are in TypeScript, Node, etc., so it's a separate repo.

Anything in particular you're looking to learn or help with?

**Comment by ppejovic** [comment]
Thanks for the reply @jeffwilcox, much appreciated. To support our innersource efforts we're looking at trying to improve the visibility of projects that are open for contribution within our enterprise. When I saw opensource.micorosft.com, specifically the _Get Involved_ part of the site, I thought running a fork of the project could potentially be a great fit for promoting innersource projects internally. 

Whilst other organizations using GitHub (Enterprise) could benefit from this as-is, in the case of my company there is gotcha, we run Azure DevOps! I was interested in taking a look at the backend code to determine the extent of rewrite that would be required to support Azure DevOps or if it would make more sense to just implement a completely separate backend that exposes the same api.

**Comment by jeffwilcox** [comment]
Yeah, unfortunately it's super specific (right now) to the schema of GitHub's webhook event processing pipeline... might be possible to get something like that rocking on top of Azure Repos, but I'm not familiar enough with that world, these days (sorry).

Will look to share what we have, though.

**Comment by Aaron-Junker** [comment]
Closing this, because it seems to be resolved.
