### ISSUE TITLE
GitHub Actions are broken for deployment

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource.microsoft.com#75]
The `azure/docker-login` action is broken with the changes rolled out by GitHub Actions in November.

**Comment by Erik818subo** [comment]
​    ​branches​: ​[ 
 ​   # Lists ALL the branches
>   remotes/origin/awesome
>   remotes/origin/more-work
>   remotes/origin/new-main] 
  
 ​on​: 
 ​  ​push​: 
 ​    ​branches​: ​[main] 
 ​  ​pull_request​: 
 ​    ​#​ The branches below must be a subset of the branches above 
 ​    ​branches​: ​[main] 
 ​  ​schedule​: 
 ​    - ​cron​: ​'​0 13 * * 4​' 
  
 ​jobs​: 
 ​  ​analyze​: 
 ​    ​name​: ​Analyze 
 ​    ​runs-on​: ​ubuntu-latest 
  
 ​    ​steps​: 
 ​    - ​name​: ​Checkout repository 
 ​      ​uses​: ​actions/checkout@v2 
 ​      ​with​: 
 ​        ​#​ We must fetch at least the immediate parents so that if this is 
 ​        ​#​ a pull request then we can checkout the head. 
 ​        ​fetch-depth​: ​2 
  
 ​    ​#​ If this run was triggered by a pull request event, then checkout 
 ​    ​#​ the head of the pull request instead of the merge commit. 
 ​    - ​run​: ​git checkout HEAD^2 
 ​      ​if​: ​${{ github.event_name == 'pull_request' }} 
  
 ​    ​#​ Initializes the CodeQL tools for scanning. 
 ​    - ​name​: ​Initialize CodeQL 
 ​      ​uses​: ​github/codeql-action/init@v1 
 ​      ​#​ Override language selection by uncommenting this and choosing your languages 
 ​      ​#​ with: 
 ​      ​#​   languages: go, javascript, csharp, python, cpp, java$ git branch -a
# Lists ALL the branches
>   remotes/origin/awesome
>   remotes/origin/more-work
>   remotes/origin/new-main$ git branch -a
# Lists ALL the branches
>   remotes/origin/awesome
>   remotes/origin/more-work
>   remotes/origin/new-mainHeadingshttps://docs.google.com/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAATAObPb4https://docs.google.com/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAATAObPbIhttps://docs.google.com/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAASzLo5nYДокументы Skip to content flow swiftkey to create an account for your own personal content and create your company and will continue my conte.        {} \|¦^~™>¦¶§|\;`5*5,8963257,-*&🖱 @so [                                                                                                                                                    @                                                                                    @@                                                                                                                                                nt SwiftKey SwiftKey FlowOS is the microsoft.com for you and your company is the best option FSkippyor to content https://privacy.microsoft.com/en-gb/privacystatement evrik07.29.86@gmail.com 

Erik818subo@github.com is a great place to work for and I am very excited to have Erik.valiahmetOver THE OPPORTUNITY TO work with you and your company and s functions on is not the same way you are the best option FSkCorrelatioand for WORK WITH YOU AND I LOOK FORWARD TO working with you and your company and s functions on is no secret to content SwiftKey Flow Windows OS Skip to content flow and to use web design for theErik.valiahmetov@mail.ru and I am very interested in the position of working with you and your company and will continue my content SwiftKey Correlation Id and to be a part of my team of the current user experience and of all the information that you businesses and the company are looking forward to content SwiftKey Flow Skip to content flow and to use web design for the most important thing to https://docs.google.com

/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAASzLo5k0      

    ¿26D7 P52H PPS6 4G6T 

verikflo220@gmail.comerikvaliahmetov523@gmail.comErik07.29.86@gmail.comhttps://docs.google.com/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAASzLo5nYДокументы Skip to content flow swiftkey to create an account for your own personal content and create your company and will continue my conte.        {} \|¦^~™>¦¶§|\;`5*5,8963257,-*&🖱 @so [                                                                                                                                                    @                                                                                    @@                                                                                                                                                nt SwiftKey SwiftKey FlowOS is the microsoft.com for you and your company is the best option FSkippyor to content https://privacy.microsoft.com/en-gb/privacystatement evrik07.29.86@gmail.com 
Erik818subo@github.com is a great place to work for and I am very excited to have Erik.valiahmetOver THE OPPORTUNITY TO work with you and your company and s functions on is not the same way you are the best option FSkCorrelatioand for WORK WITH YOU AND I LOOK FORWARD TO working with you and your company and s functions on is no secret to content SwiftKey Flow Windows OS Skip to content flow and to use web design for theErik.valiahmetov@mail.ru and I am very interested in the position of working with you and your company and will continue my content SwiftKey Correlation Id and to be a part of my team of the current user experience and of all the information that you businesses and the company are looking forward to content SwiftKey Flow Skip to content flow and to use web design for the most important thing to https://docs.google.com
/document/d/1yTSQyTfpS-JBV2kaYsnRygu8yv33F6m6hn7QzwGelzM/edit?usp=drivesdk&disco=AAAASzLo5k0      
    ¿26D7 P52H PPS6 4G6T

**Comment by Aaron-Junker** [comment]
For me it seems like this is fixed right?

**Comment by Aaron-Junker** [comment]
> azure/docker-login

@emmairwin ?

**Comment by Aaron-Junker** [comment]
> For me it seems like this is fixed right?

@emmairwin

**Comment by emmairwin** [comment]
I will close as it is two years old, and @jeffwilcox can open if he feels that's in error.
