### ISSUE TITLE
Windows Photo Viewer

### ISSUE THREAD

**Issue by Ubuntu-2020** [microsoft/opensource.microsoft.com#81]
I really like the **Windows Photo Viewer** program.
![Windows7defaultPhotoViewer](https://user-images.githubusercontent.com/65112331/104842919-a2a38780-58d0-11eb-8b8c-8239aecd7f44.jpg)

However, I already use Linux. And the Linux operating system has its own programs for **viewing images**. And some of them are very good!
But most of the programs to view images in Linux is not very user-friendly interface :-(
I believe that the **Windows Photo Viewer** program can be considered a sample of the classic interface!
I believe that this is exactly what a program for viewing images should look like!
I tried but never found the source code of this program on the site **[opensource.microsoft.com](https://opensource.microsoft.com)**

**Question: please tell me if Microsoft is planning to open the source code of the Windows Photo Viewer program in the near future?**

My question may seem strange, so I'll explain a bit. Gradually, Microsoft opens the source code of its applications, for example, a _Calculator_... Why should Microsoft do this? Everything is simple, there have been free and open calculators for a long time. Thus, Microsoft did not lose anything by opening its source code.
Also, there have been **good image viewing programs** in Linux for a long time. Thus, it seems to me that Microsoft will not lose anything by opening the source code of the **Windows Photo Viewer** program. Moreover, if you open the source code of the **Windows Photo Viewer** program and make versions for Linux users, then the community will definitely find errors in the code and offer something new to improve the program. And hackers are not asleep. They are constantly publishing something from the [source code](https://archive.is/eg9nw).

**Comment by msftgits** [comment]
Hi,
Unfortunately, the team that helps maintain this web site is not familiar with any of the plans of the many teams regarding what may be open sourced in the future, but we have passed this request along to a discussion location inside the company about open source. Thanks!
