### ISSUE TITLE
Microsoft Windows & ReactOS

### ISSUE THREAD

**Issue by Ubuntu-2020** [microsoft/opensource.microsoft.com#83]
On the site **opensource.microsoft.com** published open source projects from **Microsoft**.
Why don't you officially invite the **[ReactOS](https://en.wikipedia.org/wiki/ReactOS)** project to use them?
I think it will benefit both ReactOS and you. After all, if some original programs from Microsoft are added to ReactOS, then over time the user community will be able to find errors in them and offer new useful innovations to improve the operating system.

After all, every year more and more leaks of Microsoft Windows source code [appear](https://anonfiles.com/Ffn8u2Yaoa/Microsoft_leaked_source_code_archive_2020-09-24_torrent) on the network.

PS: I should note that in my opinion, adding programs to ReactOS should not be a simple copy (**Ctrl**+**C**). After all, Microsoft programs have **telemetry**! I would have **deleted it**. It was **deleted**, not disabled by default. If it is disabled by default, it means that it can be enabled :-(
And telemetry (_SEND_TELEMETRY_) is present even in the **[calculator](https://blogs.windows.com/windowsdeveloper/2019/03/06/announcing-the-open-sourcing-of-windows-calculator/)**!

**Comment by t12344** [comment]
𝑲 𝑵 𝑵 𝑼 ᵗᵒᵐᵃʰᵃʷᵏ
