### ISSUE TITLE
Microsoft Edge ad while browsing on Edge Canary

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/opensource.microsoft.com#89]
Not sure if it belongs here, but while browsing the [WinUI website](https://microsoft.github.io/microsoft-ui-xaml/), I got a banner for Microsoft Edge even though I was browsing it with Edge Canary - it seems the user agent recognition does not take this version of the browser into account.

![image](https://user-images.githubusercontent.com/1075116/108817893-dac97480-75b8-11eb-8b01-38e2dddca203.png)

**Comment by jeffwilcox** [comment]
Sorry, that's a different repo: https://github.com/microsoft/microsoft-ui-xaml
